import type { Metadata } from "next";
import { Inter, Spectral } from "next/font/google";
import "./globals.css";

// Load Spectral from Google Fonts
const spectral = Spectral({
  subsets: ["latin"],
  variable: "--font-spectral",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Use Inter as a substitute for General Sans
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spectral.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
